### PR TITLE
database.puml generator

### PR DESCRIPTION
**Pull request by artemohanjanyan**

### CODE REVIEW

**Comment by mityada** [comment]
PumlGenerator is not an entity. I'm not sure where it should be placed, better ask @matvey-kazakov.

**Comment by matvey-kazakov** [comment]
I think that it is reasonable to have separate module within project (split "web" part from "dev tools" or "support" or whatever). 
If it is too much work, just put it into "ru.neerc.ifmo.dev" package (outside of volunteers) and we can even remove it from production. But i think it's not big deal to keep it there just inside separate package.

**Comment by lapenok-aleksej** [comment]
Today I saw, that spring throw exception, because we can't use  `@Entity` for enum

**Comment by matvey-kazakov** [comment]
How is this related to this commit?

**Comment by lapenok-aleksej** [comment]
I think now we can merge

**Comment by artemohanjanyan** [comment]
It's probably better to move `PulmGenerate` to separate sourceset, not package.

**Pull request merged**
